### ISSUE TITLE
plans

### ISSUE THREAD

**Issue by martindurant** [dask/dask-docker#1]
What do you propose to do with this, versus the Dockerfile at https://github.com/martindurant/dask-kubernetes/blob/master/Dockerfile ?

**Comment by danielfrg** [comment]
Probably have something similar to what Jupyter have for their docker-stacks: https://github.com/jupyter/docker-stacks

I like the idea of a container that starts the Jupyter notebook but its also nice to have one with only the necessary stuff to run dask for other things, the helm chart is a good example.

**Comment by martindurant** [comment]
So would it be useful to split what I have into a couple of steps - something like yours here as the building base, and more complex derived ones? Or perhaps is it reasonable to keep them separate? In dask-kubernetes, all the services use the same image, which will be slightly wasteful for the workers.

**Comment by danielfrg** [comment]
I am ok in either case, separate or here. Docker hub is flexible and multiple images can point to one repo to centralize. What steps/levels are you thinking? I cannot think of more than than 2 or 3.

**Comment by jacobtomlinson** [comment]
Things have moved on a little here, this repo is home to mainline Dask images and is in great shape. I'm going to close this issue out.
