### ISSUE TITLE
miniconda version bump

### ISSUE THREAD

**Issue by rpanai** [dask/dask-docker#118]
Is there a particolar reason for having
```dockerfile
FROM continuumio/miniconda3:4.7.12
```
Instead of 
```dockerfile
FROM continuumio/miniconda3:4.8.2
```

**Comment by jrbourbeau** [comment]
Not that I'm aware of. We want to keep the version pinned so we don't pick up up any unexpected breaking changes. But other than that I suspect we're using `4.7.12` because no one has bumped the miniconda version in a few months.

**Comment by quasiben** [comment]
@martindurant did you recently bump the miniconda version in fastparquet or was it some other library ?

**Comment by martindurant** [comment]
Not consciously. 
I'm not even sure what i means - the CI in fastparquet is only used in fastparquet, I don't see how it could affect anyone else.

**Comment by jacobtomlinson** [comment]
> I suspect we're using 4.7.12 because no one has bumped the miniconda version in a few months.

Yup that sounds right. A PR to bump the version would be appreciated.

**Comment by rpanai** [comment]
> > I suspect we're using 4.7.12 because no one has bumped the miniconda version in a few months.
> 
> Yup that sounds right. A PR to bump the version would be appreciated.

Done! [PR](https://github.com/dask/dask-docker/pull/119)
