### ISSUE TITLE
Move default branch from "master" -> "main"

### ISSUE THREAD

**Issue by jsignell** [dask/dask-docker#139]
@jrbourbeau and I are in the process of moving the default branch for this repo from master to main. 

 - [x] Changed in GitHub
 - [x] Merged PR to change branch name in code. (#138)

### What you need to do

First: **head to your fork and rename the default branch there**
Then:
```bash
git branch -m master main
git fetch origin
git branch -u origin/main main
```

**Comment by jakirkham** [comment]
I *think* this is done, but please double check 🙂

**Comment by jakirkham** [comment]
Also submitted PR ( https://github.com/dask/dask-docker/pull/140 ) to switch a scikit-learn link to use `main` since that is now an option

**Comment by jrbourbeau** [comment]
Closing as we've finished the switch to `main` here. Thanks @jsignell @jakirkham
