### ISSUE TITLE
Add more Python versions

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/dask-docker#145]
Today I've been debugging something which ended up being a Python 3.7 v 3.8 issue where my cluster was using Docker and 3.8 and my local conda environment was 3.7.

I wonder if it would be useful to build multiple plages with different Python versions?

**Comment by NI1993** [comment]
I'm having the same issue!

**Comment by jacobtomlinson** [comment]
In #149 we added builds for `3.8` and `3.9`. I also tried to add `3.7` but there were security related issues that I couldn't get to the bottom of.

https://github.com/dask/dask-docker/runs/3340250334

```
#6 30.40 Looking for: ['python==3.7', 'cytoolz', 'dask==2021.8.0', 'lz4', 'numpy==1.21.1', 'pandas==1.3.0', 'tini==0.18.0']
#6 30.40 
#6 30.40 Encountered problems while solving:
#6 30.40   - package libnghttp2-1.43.0-h812cca2_0 requires openssl >=1.1.1i,<1.1.2a, but none of the providers can be installed
```

I'm going to close this out as we now support multiple Python versions. If there is a strong desire to go back and add `3.7` we can open a new issue to track this.
