### ISSUE TITLE
Docker Compose fails build on Win 10 and macOS

### ISSUE THREAD

**Issue by joehoeller** [dask/dask-docker#156]
```
docker-compose build base-notebook
Building base-notebook
#1 [internal] load git source github.com/jupyter/docker-stacks.git#master:base-notebook

#1 ERROR: subdir not supported yet
------
 > [internal] load git source github.com/jupyter/docker-stacks.git#master:base-notebook:
------
failed to solve with frontend dockerfile.v0: failed to read dockerfile: failed to load cache key: subdir not supported yet
Service 'base-notebook' failed to build : Build failed
```

**Comment by jacobtomlinson** [comment]
Could you please share your Docker version? Typically we support `docker-ce` on Linux and we use Ubuntu in CI.

It seems that specifying git subdirectories is not supported in all Docker build modes (buildkit).

https://github.com/docker/for-linux/issues/1102

**Comment by walter211** [comment]
I met the same Docker version 20.10.6, build 370c289

**Comment by walter211** [comment]
> Could you please share your Docker version? Typically we support `docker-ce` on Linux and we use Ubuntu in CI.
> 
> It seems that specifying git subdirectories is not supported in all Docker build modes (buildkit).
> 
> [docker/for-linux#1102](https://github.com/docker/for-linux/issues/1102)

how to solve this temporarily?

**Comment by walter211** [comment]
![WeChatWorkScreenshot_fd614990-9048-4b35-97d4-77d4817cc4ff](https://user-images.githubusercontent.com/2074640/122165838-5d997680-ceab-11eb-9084-3ac09e4ca250.png)

I clone the jupyter repo manually but is this build cost is normal？

**Comment by walter211** [comment]
MacOS Bigsur

**Comment by jacobtomlinson** [comment]
There is an existing problem with building these images using buildkit. I am wondering if buildkit became the default in Windows/macOS lately?

I am curious why you are building the images. We build these for you and publish them to DockerHub. Are you just trying to start a Dask cluster with docker? Or are you specifically trying to build the images yourself?

**Comment by joehoeller** [comment]
I was just trying to run the docker compose file like how you’re supposed
to. I did pull the image first, but then the docker compose files still
build it on its own without looking in local docker registry apparently in
windows.

Protip: I never use buildkit for my stuff and would advise to stop using
it. It creates far too many deployment problems. I normally use helm but I
have some local work that needs to be done.

**Comment by jacobtomlinson** [comment]
I wonder if the confusion here is the intent of the docker compose file. 

This repo is just for building images. The docker compose file is set up for building them every time.

I wonder if we need to shuffle things round a bit here and have two files, one for building and one for using.

**Comment by jacobtomlinson** [comment]
#171 separated the build stack from the example stack which should solve this issue.
