### ISSUE TITLE
`.github/workflows/build.yml` not updated in autoupdate

### ISSUE THREAD

**Issue by jakirkham** [dask/dask-docker#197]
The versions in `.github/workflows/build.yml` don't appear to be getting updated by the autoupdate script. For example PR ( https://github.com/dask/dask-docker/pull/196 ) doesn't include these. Though [there is this version]( https://github.com/dask/dask-docker/blob/5bd1d001f7c6c2e4bbff4133308766c711222d9e/.github/workflows/build.yml#L10 ), which we'd like to update as well.

**Comment by jakirkham** [comment]
Is there some way we need to structure the files included?

https://github.com/dask/dask-docker/blob/d36602cd96fd8e2433597f1003ee14be4f88a33f/.github/workflows/watch-conda-forge.yml#L25

**Comment by jacobtomlinson** [comment]
We might want to update the version of the `find-replace` action as it now uses glob which may be a little easier to set up.
