### ISSUE TITLE
Allow conda packages to be installed with mamba

### ISSUE THREAD

**Issue by charlesbluca** [dask/dask-docker#215]
Given that [mamba is already included](https://github.com/dask/dask-docker/blob/82a622a2efe284c74832a3efce3499853dcee471/base/Dockerfile#L13) in the base environments of `dask` and `dask-notebook`, it would be nice if users could choose to install extra conda packages with it instead of conda.

This could be done either with a variable controlling which solver to use for all conda installs (i.e `USE_MAMBA`) and/or with a separate variable specifying packages to install with mamba (i.e. `EXTRA_MAMBA_PACKAGES`).

**Comment by jacobtomlinson** [comment]
I think my preference would be `USE_MAMBA`. We could implement that to use `mamba` under the hood, or alternatively to use the `libmamba` solver with `conda`. 

It also makes it easy to flip it to default `true` at some point. I expect `conda` will also move to `libmamba` by default eventually.
