### ISSUE TITLE
[Re]build / publish images on all commits to `main`?

### ISSUE THREAD

**Issue by charlesbluca** [dask/dask-docker#223]
Currently, the setup for publishing containers looks something like:

- a commit is made to `main` which changes the `release` version in [build.yml](https://github.com/dask/dask-docker/blob/main/.github/workflows/build.yml)
- this commit triggers the [autotag workflow](https://github.com/dask/dask-docker/blob/main/.github/workflows/autotag.yml), which creates a new tag based on the value of `release`
- the creation of a new tag triggers build.yml (including the steps that actually publish the container)

This works fine on "release" commits such as https://github.com/dask/dask-docker/commit/74f2f356bd50d0068f30edc7bd9dbee8e69c3d4c, but makes it so commits to `main` that don't bump the `release` tag don't end up publishing new containers, even if they've made changes that affect the containers; to trigger a release in these cases, we must manually delete and create the latest tag.

I'm wondering if it would make sense to eliminate the autotagging from this setup entirely, so that containers would be published on all commits to `main`. If this is undesirable, maybe it would be worthwhile exploring how we could change the autotag workflow to ensure that a new tag is made on every commit (either by appending some unique string to the tag name or deleting and remaking the tag)?

**Comment by jacobtomlinson** [comment]
I've always considered this intentional. Changes made on `main` here are just like changes made on the `main` of `dask` or `distributed`. They are tested and committed and released all together on the next release.

Occasionally we do delete a tag and recreate it if we need to get a fix out urgently. 

Something we used to have in the past was `dev` tag that gets updated on every commit to `main` to allow folks to try things out, but nobody was using it and it got dropped in the migration to GitHub Actions.

**Comment by charlesbluca** [comment]
That makes sense to me - in that case, I think we can close #224 and we can continue using the current setup.

> Something we used to have in the past was `dev` tag that gets updated on every commit to main to allow folks to try things out, but nobody was using it and it got dropped in the migration to GitHub Actions.

That sounds interesting - not sure if there's any resource limitations currently making it impossible to start publishing to this tag again, but Dask-SQL's CI currently depends on the Dask docker images and using a `dev` tag there could be a good way to test the latest changes to this repo prior to release.

**Comment by jacobtomlinson** [comment]
I don't think there would be resource limitations. The only issue is the `dev` branch would be updated with changes made here, not changes made on `dask/dask` and `dask-distributed` so we might want to think about making it a nightly action to pick up new code.

**Comment by charlesbluca** [comment]
Hmm in my head I was thinking of the `dev` tag being mainly for latest changes to the Docker images themselves (i.e. changes to the Dockerfiles or scripts) rather than latest changes to Dask/Distributed. In the case of Dask-SQL, we would probably want the ability to be able to use the latest Docker images with stable or nightly Dask.

Would it make sense to have an environment variable controlling whether or not to use Dask nightlies, i.e. `USE_NIGHTLY_DASK`, which would then conda install `dask/label/dev::dask` as part of the container start up?

**Comment by jacobtomlinson** [comment]
Ok fair enough. You can always use `EXTRA_PIP_PACKAGES` and `EXTRA_CONDA_PACKAGES` env vars to install whatever versions you want at runtime. I use that in various CI environments to install from `main` for testing.
