### ISSUE TITLE
Add dask-ml notebook

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-docker#23]
@TomAugspurger I'd like to add your dask-ml notebook to our standard helm install, which uses this docker image by default.  Is the notebook that you placed in the pangeo docker image the correct one to copy here as well?  I can do this, I just wanted to check with you that you haven't made changes since then.

**Comment by TomAugspurger** [comment]
The pangeo one uses `KubeCluster`. I think https://github.com/dask/dask-examples/blob/master/machine-learning.ipynb would be the one we want.

**Comment by TomAugspurger** [comment]
We have some ML notebooks in https://github.com/dask/dask-docker/tree/master/notebook/examples/ml, so this can be closed I think.
