### ISSUE TITLE
pyarrow seems to be missing from the images

### ISSUE THREAD

**Issue by martinedgefocus** [dask/dask-docker#233]
This seems fairly fundamental and necessary? 
Per discussion here: https://dask.discourse.group/t/missing-pyarrow/796/2 it was suggested I report this here

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @martinedgefocus. As there are a wide variety of use cases where folks use Dask, we try keep the packages included by default in these images minimal but allow users to specify additional dependencies they may need installed though setting environment variables (see https://docs.dask.org/en/stable/deploying-docker.html#extensibility). For example, if you would like `pyarrow` installed you could set `EXTRA_CONDA_PACKAGES="-c conda-forge pyarrow"`

**Comment by martinedgefocus** [comment]
OK, thanks. I'm new to this I'm afraid.
The environment we set up is an AWS EC2Cluster with automatic sizing per the adapt() mechanism.
Is it still feasible to pass the environment variables through like that to add extra packages?
I can see there's an env_vars param, would that be sufficient?

**Comment by jacobtomlinson** [comment]
Yup that is one of the intended uses of `env_vars`, those variables are passed to the `docker run` command that happens under the hood on the EC2 instances.

```python
cluster = EC2Cluster(..., env_vars={"EXTRA_CONDA_PACKAGES": "pyarrow"})
```

I'm going to close this out but please feel free to follow up here if you have more questions about how to do this.
