### ISSUE TITLE
crash when use tensorflow 2.9.1 in dask-notebook

### ISSUE THREAD

**Issue by RexHuang** [dask/dask-docker#238]
**What happened**:
crash when use tensorflow 2.9.1 in dask-notebook

**What you expected to happen**:
import tensorflow as tf

**Minimal Complete Verifiable Example**:
pip install tensorflow with root user

import tensorflow as tf in notebook

pop up window says "Kernel Restarting"

docker logs:
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control
[IPKernelApp] WARNING | No such comm: 3106bc1f-6f0f-42c1-923b-1e8dc45105b8

```python
# Put your MCVE code here
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2022.3.0-py3.8
- Python version: 3.8
- Operating System: CentOS Linux 7
- Install method (conda, pip, source):

<details>
<summary>Cluster Dump State:</summary>

</details>

**Comment by jacobtomlinson** [comment]
I'm afraid I am unable to reproduce with the latest release:

```console
$ docker run --rm -p 8888:8888 ghcr.io/dask/dask-notebook:2022.6.1 --ip=0.0.0.0
```

```python
!pip install tensorflow
import tensorflow as tf  # Works
```

<img width="854" alt="image" src="https://user-images.githubusercontent.com/1610850/176417748-35bd6263-b312-4134-9bce-f826e70b36e0.png">

**Comment by RexHuang** [comment]
Thanks jacobtomlinson,
I had re-try with clean install of 2022.3.0-py3.8, it works fine.
close the issue.
