### ISSUE TITLE
Support of extra jupyterlab extention

### ISSUE THREAD

**Issue by jderuere** [dask/dask-docker#29]
It would be nice to support jupyterlab extention in dask-notebook.
Something like this in the prepare.sh:

```
if [ "$EXTRA_JL_EXTENTIONS" ]; then  
    echo "EXTRA_JL_EXTENTIONS environment variable found.  Installing."  
    jupyter labextension install $EXTRA_JL_EXTENTIONS  
fi
```

**Comment by danielfrg** [comment]
Sorry we didn't reply. 

Stuff like this is recommended to put it in the actual docker image so they don't have to be installed everytime the container runs. So I would recommend to extend the image to your own or just add the extensions to you want to the Dockerfile in this repo.
