### ISSUE TITLE
Add cachey dependency

### ISSUE THREAD

**Issue by asherp** [dask/dask-docker#43]
I know this feature is considered experimental, but is there any chance of making cachey a dependency?

**Comment by mrocklin** [comment]
Would be fine with me

**Comment by martindurant** [comment]
@asherp , it would probably be best to submit a PR with the added dependency

**Comment by asherp** [comment]
Since then I've also found your streamz library to be very useful and was wondering if I should include it as well. Are there other dask-related projects that should be included? Thanks

**Comment by martindurant** [comment]
I guess going broad is OK so long as the image size does not increase appreciably.

**Comment by quasiben** [comment]
@asherp any plans on submitting a PR ?  If not, totally fine.
