### ISSUE TITLE
joblib error with docker workers

### ISSUE THREAD

**Issue by sandys** [dask/dask-docker#53]
this is the script im running

```
from sklearn.datasets import make_classification
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
import numpy as np
import pandas as pd


X, y = make_classification(n_samples=1000, random_state=0)
X[:5]

param_grid = {"C": np.logspace(-3, 1, 30),
              "gamma": [0.05, 0.5, 2],
              "kernel": ['rbf', 'poly', 'sigmoid'],
              "shrinking": [True, False]}

grid_search = GridSearchCV(SVC(gamma='auto', random_state=0, probability=True),
                           param_grid=param_grid,
                           return_train_score=False,
                           iid=True,
                           cv=3,
                           n_jobs=-1)



from sklearn.externals import joblib
dask_scheduler='172.17.0.1'

with joblib.parallel_backend('dask',scheduler_host=dask_scheduler+":8786", scatter=[X, y]):
    grid_search.fit(X, y)

```

I get the following error 

>>>distributed.protocol.pickle - INFO - Failed to deserialize b'\x80\x04\x95Q\x03\x00\x00\x00\x00\x00\x00\x8c\x0cjoblib._dask\x94\x8c\x05Batch\x94\x93\x94]\x94\x8c#sklearn.model_selection._validation\x94\x8c\x0e_fit_and_score\x94\x93\x94]\x94(\x8c\x13sklearn.svm.classes\x94\x8c\x03SVC\x94\x93\x94)\x81\x94}\x94(\x8c\x17decision_function_shape\x94\x8c\x03ovr\x94\x8c\x06kernel\x94\x8c\x03rbf\x94\x8c\x06degree\x94K\x03\x8c\x05gamma\x94\x8c\x04auto\x94\x8c\x05coef0\x94G\x00\x00\x00\x00\x00\x00\x00\x00\x8c\x03tol\x94G?PbM\xd2\xf1\xa9\xfc\x8c\x01C\x94G?\xf0\x00\x00\x00\x00\x00\x00\x8c\x02nu\x94G\x00\x00\x00\x00\x00\x00\x00\x00\x8c\x07epsilon\x94G\x00\x00\x00\x00\x00\x00\x00\x00\x8c\tshrinking\x94\x88\x8c\x0bprobability\x94\x88\x8c\ncache_size\x94K\xc8\x8c\x0cclass_weight\x94N\x8c\x07verbose\x94\x89\x8c\x08max_iter\x94J\xff\xff\xff\xff\x8c\x0crandom_state\x94K\x00\x8c\x10_sklearn_version\x94\x8c\x060.21.2\x94ub\x8c\x11distributed.utils\x94\x8c\nitemgetter\x94\x93\x94K\x00\x85\x94R\x94h$K\x01\x85\x94R\x94e}\x94(\x8c\x05train\x94h$K\x02\x85\x94R\x94\x8c\x04test\x94h$K\x03\x85\x94R\x94\x8c\nparameters\x94}\x94(h\x16\x8c\x15numpy.core.multiarray\x94\x8c\x06scalar\x94\x93\x94\x8c\x05numpy\x94\x8c\x05dtype\x94\x93\x94\x8c\x02f8\x94K\x00K\x01\x87\x94R\x94(K\x03\x8c\x01<\x94NNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00t\x94bC\x08\xfc\xa9\xf1\xd2MbP?\x94\x86\x94R\x94h\x12G?\xa9\x99\x99\x99\x99\x99\x9ah\x0fh\x10h\x19\x88u\x8c\x06scorer\x94}\x94\x8c\x05score\x94\x8c\x16sklearn.metrics.scorer\x94\x8c\x13_passthrough_scorer\x94\x93\x94s\x8c\nfit_params\x94}\x94\x8c\x12return_train_score\x94\x89\x8c\x15return_n_test_samples\x94\x88\x8c\x0creturn_times\x94\x88\x8c\x11return_parameters\x94\x89\x8c\x0berror_score\x94\x8c\x11raise-deprecating\x94h\x1dK\x00u\x87\x94a\x85\x94R\x94.'
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/distributed/protocol/pickle.py", line 61, in loads
    return pickle.loads(x)
ModuleNotFoundError: No module named 'joblib'
distributed.worker - WARNING - Could not deserialize task
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/distributed/worker.py", line 1272, in add_task
    self.tasks[key] = _deserialize(function, args, kwargs, task)
  File "/opt/conda/lib/python3.7/site-packages/distributed/worker.py", line 3060, in _deserialize
    function = pickle.loads(function)
  File "/opt/conda/lib/python3.7/site-packages/distributed/protocol/pickle.py", line 61, in loads
    return pickle.loads(x)
ModuleNotFoundError: No module named 'joblib'

**Comment by sandys** [comment]
just the clarify the error is being issued from the worker, so the distribution is being happening.

**Comment by jrbourbeau** [comment]
Thanks for raising this issue @sandys. `joblib` is not currently included in the dask images, but can be added at runtime by specifying certain environment variables, e.g. `EXTRA_CONDA_PACKAGES="joblib"`. See https://docs.dask.org/en/latest/setup/docker.html#extensibility for how to customize the dask images to include additional packages.

**Comment by sandys** [comment]
Hi
Thanks for replying.

Any reason this is so ? Because the example is a trivial example from your
own site.

Effectively these examples are unrunnable because the missing dependency.

It would be great if you could add them in.

**Comment by TomAugspurger** [comment]
These images are used by many downstream users, many of which won't need joblib. Including it in the base image isn't appropriate.

**Comment by jrbourbeau** [comment]
The docker images maintained in this repository are to help set up Dask + the distributed scheduler. However, `joblib` is not a dependency for either `dask/dask` or `dask/distributed`, which is why it's not included by default.

In the above example, `joblib` is using `dask` as a dependent library. Using environment variables like `EXTRA_CONDA_PACKAGES` should help in adding any non-required, external packages you may require to the Dask docker containers.

**Comment by jrbourbeau** [comment]
Good timing @TomAugspurger : )

**Comment by jrbourbeau** [comment]
Closing as the originally posted issue has been resolved

**Comment by gustavomr** [comment]
use this command "docker run -it -e EXTRA_CONDA_PACKAGES="joblib" daskdev/dask dask-worker localhost:8786"
