### ISSUE TITLE
docker workers fails to deserialize with rasterio 

### ISSUE THREAD

**Issue by PhenoloBoy** [dask/dask-docker#54]
Hi, 

after a deploy over GC of a Dask chart using Helm I've update the environment with some extra conda packages, specifically xarray and rasterio.
 If I try to run my code I'm getting back this error from the workers log.

`Traceback (most recent call last): File "/opt/conda/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback ret = callback() File "/opt/conda/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result future.result() File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 742, in run yielded = self.gen.throw(*exc_info) # type: ignore File "/opt/conda/lib/python3.7/site-packages/distributed/worker.py", line 661, in handle_scheduler self.ensure_computing]) File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 735, in run value = future.result() File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 742, in run yielded = self.gen.throw(*exc_info) # type: ignore File "/opt/conda/lib/python3.7/site-packages/distributed/core.py", line 386, in handle_stream msgs = yield comm.read() File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 735, in run value = future.result() File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 742, in run yielded = self.gen.throw(*exc_info) # type: ignore File "/opt/conda/lib/python3.7/site-packages/distributed/comm/tcp.py", line 206, in read deserializers=deserializers) File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 735, in run value = future.result() File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper yielded = next(result) File "/opt/conda/lib/python3.7/site-packages/distributed/comm/utils.py", line 82, in from_frames res = _from_frames() File "/opt/conda/lib/python3.7/site-packages/distributed/comm/utils.py", line 68, in _from_frames deserializers=deserializers) File "/opt/conda/lib/python3.7/site-packages/distributed/protocol/core.py", line 132, in loads value = _deserialize(head, fs, deserializers=deserializers) File "/opt/conda/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 184, in deserialize return loads(header, frames) File "/opt/conda/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 57, in pickle_loads return pickle.loads(b''.join(frames)) File "/opt/conda/lib/python3.7/site-packages/distributed/protocol/pickle.py", line 59, in loads return pickle.loads(x) File "/opt/conda/lib/python3.7/site-packages/rasterio/__init__.py", line 22, in <module> from rasterio._base import gdal_version ImportError: libzstd.so.1: cannot open shared object file: No such file or directory
`
For my understanding problem seems to be the missing or corrupted library libzstdl , am I right?
Any idea?

**Comment by TomAugspurger** [comment]
I suspect this isn't a dask-docker issue.

Can you provide a minimal example?

Can you pickle a rasterio object?

**Comment by PhenoloBoy** [comment]
Adding in the config.yaml file the line:

`  env:
    - name: EXTRA_APT_PACKAGES
      value : libzstd1`

te problem seems to be solved

but looking here and there for the solution I've now a new doubt. 
In the readme it's written: 
> This images are built primarily for the dask-distributed Helm Chart but they should work for more use cases.

if you have a look in the helm repo, and specifically in the [value](https://github.com/helm/charts/blob/master/stable/dask/values.yaml) file I can see that it's pointing to the repository: "daskdev/dask" . Is it correct? I'm asking becouse installing trough helm I've some probelm and as the user is set to jovyan I've to understand better who can help me.
