### ISSUE TITLE
no 2.6.0 tag

### ISSUE THREAD

**Issue by DeoLeung** [dask/dask-docker#65]
it seems it only tags `latest/dev`, add a proper version tag like `2.6.0` will be great

**Comment by jacobtomlinson** [comment]
There hasn't been a `2.6.0` release from here yet, hence the missing tag. Will get on this now.

**Comment by jacobtomlinson** [comment]
Just done a release and the `2.6.0` tag is now available on Docker Hub.

**Comment by jrbourbeau** [comment]
Thanks @jacobtomlinson!
