### ISSUE TITLE
lz4 dependency

### ISSUE THREAD

**Issue by kmadathil** [dask/dask-docker#66]
As noted in https://github.com/dask/distributed/issues/3209, the helm/kubernetes [documentation](https://docs.dask.org/en/latest/setup/kubernetes-helm.html) for dask leads to an issue if the client computer has lz4 installed. 

It may be better to include the lz4 conda package in the daskdev/dask image to avoid this.

**Comment by jacobtomlinson** [comment]
I've moved this issue to dask/dask-docker as this is a question about what packages should be included in the Dask docker image that is used by the helm chart.

The suggestion from @kmadathil in dask/distributed#3209 is:
> To avoid this error, I suggest upgrading the daskdev/dask container to include all the compression packages that dask could use.

There is definitely a tradeoff between providing everything folks could want out of the box vs having a bloated image that is big and annoying to download.

Personally I think packages like `lz4` are common and reasonable but would love to get thoughts from others on where we should draw lines. cc @mrocklin @TomAugspurger

**Comment by TomAugspurger** [comment]
While it'd be nice to solve this upstream, I think that including it in the
docker image seems fine. It seems to be
a pretty small download.

**Comment by kmadathil** [comment]
If I may chime in:

Include only those packages that could cause non-obvious errors for someone starting out, given the philosophy that it's better to keep the new user's path as simple as possible. This will allow the list of included packages to be minimized. 
 
Once more verbose reporting of this sort of situation as in dask/distributed#2627 is live, the need for this will be mitigated somewhat.

**Comment by jacobtomlinson** [comment]
I agree @kmadathil. However I think `only those packages that could cause non-obvious errors for someone starting out` is going to be rather subjective. 

It seems we are all in agreement to add `lz4` to the docker image. Do you have any interest in raising a PR?

**Comment by kmadathil** [comment]
Sure. I will do that.
