### ISSUE TITLE
dask-docker: Licensing

### ISSUE THREAD

**Issue by andremoeller** [dask/dask-docker#75]
Hello,

I'm wondering: is this software released under a license, like Apache 2.0, MIT, etc.? If so, could you add a LICENSE, like so: https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository

Dask itself is licensed under New BSD: https://github.com/dask/dask#license

Thank you!

**Comment by jrbourbeau** [comment]
Thanks for bringing this up @andremoeller! We should certainly have some sort of license for this repository. I personally don't have a strong preference between any of the permissive licenses like New BSD, MIT, etc. (would probably default to New BSD as that's what `dask/dask` uses)

cc @jacobtomlinson @mrocklin @jcrist who may or may not have a strong opinion on the topic

**Comment by jcrist** [comment]
New bsd makes sense to me

**Comment by jacobtomlinson** [comment]
Given various employers will have signed off on contributing to Dask under the New BSD license it makes sense to continue being consistent.

We should probably default all Dask subprojects to that license.
