### ISSUE TITLE
No 2.12.0 tag

### ISSUE THREAD

**Issue by JulianWgs** [dask/dask-docker#92]
Hello,

could you please add a 2.12.0 tag?

Thank you!

Is there any way to automate this, since I saw other issues with missing issues?

**Comment by jrbourbeau** [comment]
Thanks for raising this issue @JulianWgs. I've pushed tags for [2.12.0](https://hub.docker.com/layers/daskdev/dask/2.12.0/images/sha256-28dd0274edea46155676cae0bfc9042adfba1aa76824914fdfc2847f072411f1?context=explore) and [2.13.0](https://hub.docker.com/layers/daskdev/dask/2.13.0/images/sha256-56b1e6d21d87f3afd64db7c0132d07c20ed6b745350516ed6459bc9f9a0a9d6e?context=explore)

Improvements to the release procedure are welcome. Right now tagging is the only manual step
