### ISSUE TITLE
latest image is 2.13 instead of 2.15

### ISSUE THREAD

**Issue by mgsnuno** [dask/dask-docker#95]
latest docker hub image is `2.13` instead of `2.15` released in 24-04. 

Noticed this while using `dask-kubernetes` and `client.get_versions(check=True)`.

I guess this is tied to: https://github.com/dask/dask-docker/pull/94/files

If the pull request gets merged does it solve the issue? Thanks

**Comment by TomAugspurger** [comment]
Merged https://github.com/dask/dask-docker/pull/94.
